# Generated by Django 4.2.23 on 2025-08-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_precios', models.BooleanField(default=True)),
                ('mostrar_contacto', models.BooleanField(default=True)),
                ('mostrar_testimonios', models.BooleanField(default=True)),
                ('modo_mantenimiento', models.BooleanField(default=False)),
                ('mensaje_mantenimiento', models.TextField(blank=True, default='Sitio en mantenimiento. Volveremos pronto.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='TelTec Net', max_length=200)),
                ('direccion', models.CharField(default='Av. Principal 123, Centro', max_length=300)),
                ('telefono', models.CharField(default='0999859689', max_length=20)),
                ('email', models.EmailField(default='info@teltecnet.com', max_length=254)),
                ('ruc', models.CharField(default='1234567890001', max_length=20)),
                ('horario', models.CharField(default='Lunes a Viernes: 8:00 AM - 6:00 PM', max_length=200)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='InformacionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='TelTec Net - Proveedor de Internet', max_length=200)),
                ('subtitulo', models.CharField(default='Conectando comunidades con tecnología de vanguardia', max_length=300)),
                ('descripcion', models.TextField(default='Somos una empresa líder en servicios de internet de alta velocidad, comprometida con brindar conectividad confiable y soporte técnico excepcional.')),
                ('lema', models.CharField(default='Conectando tu mundo digital', max_length=200)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información del Sitio',
                'verbose_name_plural': 'Información del Sitio',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=20)),
                ('url', models.URLField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'unique_together': {('tipo',)},
            },
        ),
    ]
