# Generated by Django 4.2.7 on 2025-08-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0001_initial'),
    ]

    operations = [
        # Limpiar la tabla RedSocial para evitar conflictos
        migrations.RunSQL(
            "DELETE FROM sitio_web_redsocial;",
            reverse_sql=""
        ),
    ]
