# Generated by Django 4.2.7 on 2025-08-25 15:37

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0002_auto_20250825_1515'),
    ]

    operations = [
        # Crear tabla Plan
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('velocidad', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('caracteristicas', models.JSONField(default=list)),
                ('popular', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['orden', 'precio'],
            },
        ),
        # Crear tabla Cobertura
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('coordenadas', models.JSONField(default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cobertura',
                'verbose_name_plural': 'Coberturas',
                'ordering': ['orden', 'zona'],
            },
        ),
        # Crear tabla Contacto
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('telefono', 'Teléfono'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('direccion', 'Dirección'), ('horario', 'Horario')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=300)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['orden', 'tipo'],
            },
        ),
        # Crear tabla Carrusel
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.URLField()),
                ('video', models.URLField(blank=True, null=True)),
                ('enlace', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrusel',
                'verbose_name_plural': 'Carrusel',
                'ordering': ['orden', 'titulo'],
            },
        ),
        # Crear tabla Header
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('logo_alt', models.CharField(default='TelTec Net Logo', max_length=200)),
                ('mostrar_menu', models.BooleanField(default=True)),
                ('color_fondo', models.CharField(default='#ffffff', max_length=7)),
                ('color_texto', models.CharField(default='#000000', max_length=7)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Header',
            },
        ),
        # Crear tabla Footer
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_copyright', models.CharField(default='© 2025 T&T net - Todos los derechos reservados', max_length=300)),
                ('mostrar_redes_sociales', models.BooleanField(default=True)),
                ('mostrar_contacto', models.BooleanField(default=True)),
                ('color_fondo', models.CharField(default='#1f2937', max_length=7)),
                ('color_texto', models.CharField(default='#ffffff', max_length=7)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
    ]
