# Generated by Django 4.2.7 on 2025-08-25 16:02

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0004_auto_20250825_1537'),
    ]

    operations = [
        # Agregar campos faltantes al modelo Servicio
        migrations.AddField(
            model_name='servicio',
            name='icono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
