# Generated by Django 4.2.23 on 2026-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0006_redsocial_fecha_creacion_redsocial_icono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('plan', models.CharField(blank=True, max_length=100, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('agendado', 'Agendado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Instalación',
                'verbose_name_plural': 'Solicitudes de Instalación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(default='teltecnet@outlook.com', max_length=254),
        ),
    ]
