# Generated by Django 4.2.23 on 2026-07-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
