# Generated by Django 4.2.23 on 2026-07-26 22:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_remove_cliente_precio_plan_remove_cliente_sector_and_more'),
        ('planes_app', '0002_alter_plan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_anio', models.DateField(help_text='Fecha del mes por el cual se debe el pago', verbose_name='Mes/Año de la deuda')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite para el pago', verbose_name='Fecha de vencimiento')),
                ('monto_deuda', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto de la deuda')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto pagado')),
                ('estado', models.CharField(choices=[('al_dia', 'Al Día'), ('proximo_vencimiento', 'Próximo Vencimiento'), ('vencido', 'Vencido'), ('pagado', 'Pagado')], default='vencido', max_length=20, verbose_name='Estado de la deuda')),
                ('meses_atraso', models.PositiveIntegerField(default=0, verbose_name='Meses de atraso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='clientes.cliente', verbose_name='Cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='planes_app.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'db_table': 'deudas',
                'ordering': ['-mes_anio', 'cliente__nombres'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('creacion', 'Creación'), ('pago', 'Pago'), ('ajuste', 'Ajuste'), ('cambio_estado', 'Cambio de Estado'), ('eliminacion', 'Eliminación')], max_length=20, verbose_name='Tipo de cambio')),
                ('descripcion', models.TextField(verbose_name='Descripción del cambio')),
                ('monto_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto anterior')),
                ('monto_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto nuevo')),
                ('estado_anterior', models.CharField(blank=True, choices=[('al_dia', 'Al Día'), ('proximo_vencimiento', 'Próximo Vencimiento'), ('vencido', 'Vencido'), ('pagado', 'Pagado')], max_length=20, null=True, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(blank=True, choices=[('al_dia', 'Al Día'), ('proximo_vencimiento', 'Próximo Vencimiento'), ('vencido', 'Vencido'), ('pagado', 'Pagado')], max_length=20, null=True, verbose_name='Estado nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario que realizó el cambio')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='deudas.deuda', verbose_name='Deuda')),
            ],
            options={
                'verbose_name': 'Historial de Deuda',
                'verbose_name_plural': 'Historial de Deudas',
                'db_table': 'historial_deudas',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='deuda',
            index=models.Index(fields=['cliente', 'estado'], name='deudas_cliente_f17647_idx'),
        ),
        migrations.AddIndex(
            model_name='deuda',
            index=models.Index(fields=['fecha_vencimiento'], name='deudas_fecha_v_e9b3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='deuda',
            index=models.Index(fields=['estado', 'meses_atraso'], name='deudas_estado_cbcffc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deuda',
            unique_together={('cliente', 'plan', 'mes_anio')},
        ),
    ]
