# Generated by Django 4.2.23 on 2026-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_planes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteplan',
            name='id',
            field=models.AutoField(db_column='id_cliente_plan', primary_key=True, serialize=False),
        ),
    ]
