# Generated by Django 4.2.23 on 2025-08-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuracion',
            table='configuracion_notificaciones',
        ),
    ]
