# Generated by Django 4.2.23 on 2025-08-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_configuracion_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracion',
        ),
    ]
