# Generated by Django 4.2.23 on 2025-08-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_delete_configuracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlamadaAutomatizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('servicio', models.CharField(choices=[('twilio', 'Twilio'), ('plivo', 'Plivo'), ('nexmo', 'Nexmo/Vonage')], default='twilio', max_length=20)),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('fallida', 'Fallida'), ('cancelada', 'Cancelada')], default='iniciada', max_length=20)),
                ('fecha_llamada', models.DateTimeField(auto_now_add=True)),
                ('duracion', models.IntegerField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('call_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Llamada Automatizada',
                'verbose_name_plural': 'Llamadas Automatizadas',
                'db_table': 'llamadas_automatizadas',
                'ordering': ['-fecha_llamada'],
            },
        ),
    ]
