# Generated by Django 4.2.23 on 2025-08-23 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_llamadaautomatizada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LlamadaAutomatizada',
        ),
    ]
