# Generated by Django 4.2.23 on 2026-07-26 22:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0005_delete_llamadaautomatizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('pago_proximo', 'Pago Próximo'), ('pago_vencido', 'Pago Vencido'), ('corte_servicio', 'Corte de Servicio'), ('recordatorio', 'Recordatorio'), ('promocion', 'Promoción'), ('mantenimiento', 'Mantenimiento')], max_length=20)),
                ('mensaje', models.TextField(help_text='Usa {nombre}, {deuda}, {plan}, {telefono} como variables')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Lista de variables disponibles: ["{nombre}", "{deuda}", "{plan}"]')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificación',
                'db_table': 'plantillas_notificacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('fallido', 'Fallido'), ('rebotado', 'Rebotado')], default='enviado', max_length=20)),
                ('proveedor', models.CharField(help_text='WhatsApp, Email, SMS, etc.', max_length=50)),
                ('referencia_externa', models.CharField(blank=True, help_text='ID del mensaje en el proveedor', max_length=255, null=True)),
                ('respuesta_proveedor', models.JSONField(blank=True, default=dict)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('errores', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de Envío',
                'verbose_name_plural': 'Registros de Envío',
                'db_table': 'registros_envio',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, help_text='Fecha programada para envío', null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='intentos',
            field=models.IntegerField(default=0, help_text='Número de intentos de envío'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='canal',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='whatsapp', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('pago_proximo', 'Pago Próximo'), ('pago_vencido', 'Pago Vencido'), ('corte_servicio', 'Corte de Servicio'), ('recordatorio', 'Recordatorio'), ('promocion', 'Promoción'), ('mantenimiento', 'Mantenimiento')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['estado'], name='notif_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo'], name='notif_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['fecha_creacion'], name='notif_fecha_crea_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['cliente_id', 'estado'], name='notif_cliente_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='notif_estado_fecha_idx'),
        ),
        migrations.AddField(
            model_name='registroenvio',
            name='notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_envio', to='notificaciones.notificacion'),
        ),
        migrations.AddIndex(
            model_name='registroenvio',
            index=models.Index(fields=['notificacion'], name='reg_notif_idx'),
        ),
        migrations.AddIndex(
            model_name='registroenvio',
            index=models.Index(fields=['estado'], name='reg_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='registroenvio',
            index=models.Index(fields=['fecha_envio'], name='reg_fecha_idx'),
        ),
    ]
