[tool.pyright]
include = [
    "."
]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "**/migrations",
    "**/venv"
]
venvPath = "."
venv = "venv"
pythonPath = "venv/bin/python"
extraPaths = [
    "venv/lib/python3.9/site-packages"
]
reportMissingImports = "warning"
reportMissingTypeStubs = false
pythonVersion = "3.9"
typeCheckingMode = "basic"

