# Generated by Django 4.2.23 on 2025-08-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('servicios', 'Servicios'), ('equipos', 'Equipos'), ('mantenimiento', 'Mantenimiento'), ('personal', 'Personal'), ('marketing', 'Marketing'), ('otros', 'Otros')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_gasto', models.DateField()),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque')], max_length=20, null=True)),
                ('comprobante_url', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'db_table': 'gastos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('deposito', 'Depósito'), ('tarjeta', 'Tarjeta'), ('pago_online', 'Pago Online')], max_length=20)),
                ('concepto', models.TextField()),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente'), ('fallido', 'Fallido')], default='completado', max_length=20)),
                ('comprobante_enviado', models.BooleanField(default=False)),
                ('numero_comprobante', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
